language: php

git:
  strategy: clone
  depth: 1
  quiet: true

# todo
# dist: bionic

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
    # todo add 7.3, 7.4

env:
  global:
    - PGPORT=5432
  jobs:
    - DB=agnostic #only database agnostic tests
    - DB=mysql
    - DB=sqlite

services:
  - mysql

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install

before_script:
  - if [[ $DB != 'agnostic' && $DB != 'sqlite' ]]; then ./tests/bin/setup.$DB.sh; fi

script:
  - ./vendor/bin/phpunit -v -c tests/$DB.phpunit.xml;

jobs:
  include:
    - php: 5.6
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1
    - php: 7.2
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: 10.1
        # todo add 10.1, 10.2, 10.3, 10.4

    - php: 5.6
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.0
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.1
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.2
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4

    - php: 5.6
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5
    - php: 7.0
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5
    - php: 7.1
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5
    - php: 7.2
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5

    - php: 5.6
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.0
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.1
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.2
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
        # todo introduce pgsql 10, 11, 12

  allow_failures:
    - php: nightly

  fast_finish: true

# cache vendors
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  webhooks:
    - http://propel.jarves.io/build.php
    - https://webhooks.gitter.im/e/206efe76e183f9ade489
