language: php

git:
  strategy: clone
  depth: 1
  quiet: true

dist: bionic

env:
  global:
    - PGPORT=5432

services:
  - mysql

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install -v
  - composer show
  - php --ini
  - php --modules
  - sqlite3 --version

before_script:
  - if [[ $DB != 'agnostic' && $DB != 'sqlite' ]]; then ./tests/bin/setup.$DB.sh; fi

script:
  - ./vendor/bin/phpunit -v -c tests/$DB.phpunit.xml

jobs:
  include:

    - name: "mysql sf ^42"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony42-min.json composer install
        - composer show
    - name: "mysql sf ^4.3.0"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony430-min.json composer install
        - composer show
    - name: "mysql sf ^4.3.5"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony435-min.json composer install
        - composer show

  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  webhooks:
    - http://propel.jarves.io/build.php
    - https://webhooks.gitter.im/e/206efe76e183f9ade489
