language: php

git:
  strategy: clone
  depth: 1
  quiet: true

dist: bionic

env:
  global:
    - PGPORT=5432

services:
  - mysql

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install -v
  - composer show
  - php --ini
  - php --modules
  - sqlite3 --version

before_script:
  - if [[ $DB != 'agnostic' && $DB != 'sqlite' ]]; then ./tests/bin/setup.$DB.sh; fi

script:
  - ./vendor/bin/phpunit -v -c tests/$DB.phpunit.xml

jobs:
  include:

    - php: nightly
      env: DB=agnostic
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-php8.json composer install
        - composer show
    - php: nightly
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-php8.json composer install
        - composer show
    - php: nightly
      env: DB=sqlite
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-php8.json composer install
        - composer show

    - name: "mysql sf ^4"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony4-min.json composer install
        - composer show
    - name: "mysql sf ^41"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony41-min.json composer install
        - composer show
    - name: "mysql sf ^42"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony42-min.json composer install
        - composer show
    - name: "mysql sf ^43"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony43-min.json composer install
        - composer show
    - name: "mysql sf ^44"
      php: 7.4
      env: DB=mysql
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - COMPOSER=./tests/composer/composer-symfony44-min.json composer install
        - composer show


  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  webhooks:
    - http://propel.jarves.io/build.php
    - https://webhooks.gitter.im/e/206efe76e183f9ade489
