language: php

git:
  strategy: clone
  depth: 1
  quiet: true

dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  global:
    - PGPORT=5432
  jobs:
    - DB=agnostic #only database agnostic tests
    - DB=mysql
    - DB=sqlite

services:
  - mysql

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install

before_script:
  - if [[ $DB != 'agnostic' && $DB != 'sqlite' ]]; then ./tests/bin/setup.$DB.sh; fi

script:
  - ./vendor/bin/phpunit -v -c tests/$DB.phpunit.xml;

jobs:
  include:
# Travis-ci doesn't know how to install Maria 10.1
#   - php: 7.1
#     env: DB=mysql MARIADB=10.1
#     addons:
#       mariadb: 10.1
#   - php: 7.2
#     env: DB=mysql MARIADB=10.1
#     addons:
#       mariadb: 10.1
#   - php: 7.3
#     env: DB=mysql MARIADB=10.1
#     addons:
#       mariadb: 10.1
#   - php: 7.4
#     env: DB=mysql MARIADB=10.1
#     addons:
#       mariadb: 10.1
#       TODO maria 5.5 is not EOL yet.

    - php: 7.1
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2
    - php: 7.2
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2
    - php: 7.3
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2
    - php: 7.4
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2

    - php: 7.1
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2
    - php: 7.2
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2
    - php: 7.3
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2
    - php: 7.4
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: 10.2

    - php: 7.1
      env: DB=mysql MARIADB=10.3
      addons:
        mariadb: 10.3
    - php: 7.2
      env: DB=mysql MARIADB=10.3
      addons:
        mariadb: 10.3
    - php: 7.3
      env: DB=mysql MARIADB=10.3
      addons:
        mariadb: 10.3
    - php: 7.4
      env: DB=mysql MARIADB=10.3
      addons:
        mariadb: 10.3

    - php: 7.1
      env: DB=mysql 4ARIADB=10.4
      addons:
        mariadb: 10.4
    - php: 7.2
      env: DB=mysql 4ARIADB=10.4
      addons:
        mariadb: 10.4
    - php: 7.3
      env: DB=mysql 4ARIADB=10.4
      addons:
        mariadb: 10.4
    - php: 7.4
      env: DB=mysql 4ARIADB=10.4
      addons:
        mariadb: 10.4

    - php: 7.1
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.2
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.3
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4
    - php: 7.4
      env: DB=pgsql POSTGRES=9.4
      addons:
        postgresql: 9.4

    - php: 7.1
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5
    - php: 7.2
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5
    - php: 7.3
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5
    - php: 7.4
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: 9.5

    - php: 7.1
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.2
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.3
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.4
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6

    - php: 7.1
      env: DB=pgsql POSTGRES=10
      addons:
        postgresql: 10
    - php: 7.2
      env: DB=pgsql POSTGRES=10
      addons:
        postgresql: 10
    - php: 7.3
      env: DB=pgsql POSTGRES=10
      addons:
        postgresql: 10
    - php: 7.4
      env: DB=pgsql POSTGRES=10
      addons:
        postgresql: 10

    - php: 7.1
      env: DB=pgsql POSTGRES=11
      addons:
        postgresql: 11
    - php: 7.2
      env: DB=pgsql POSTGRES=11
      addons:
        postgresql: 11
    - php: 7.3
      env: DB=pgsql POSTGRES=11
      addons:
        postgresql: 11
    - php: 7.4
      env: DB=pgsql POSTGRES=11
      addons:
        postgresql: 11

# Travis-ci doesn't know how to install postgres 12
#   - php: 7.1
#     env: DB=pgsql POSTGRES=12
#     addons:
#       postgresql: 12
#   - php: 7.3
#     env: DB=pgsql POSTGRES=12
#     addons:
#       postgresql: 12
#   - php: 7.4
#     env: DB=pgsql POSTGRES=12
#     addons:
#       postgresql: 12
#   - php: 7.2
#     env: DB=pgsql POSTGRES=12
#     addons:
#       postgresql: 12


  allow_failures:
    - php: nightly

  fast_finish: true

# cache vendors
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  webhooks:
    - http://propel.jarves.io/build.php
    - https://webhooks.gitter.im/e/206efe76e183f9ade489
