language: php

php:
  - 7.2
  - 7.3
  - nightly

env:
  - DB=agnostic #only database agnostic tests
  - DB=mysql
  - DB=sqlite

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install

before_script:
  - if [[ $DB != 'agnostic' && $DB != 'sqlite' ]]; then ./tests/bin/setup.$DB.sh; fi

script:
  - ./vendor/bin/phpunit -v -c tests/$DB.phpunit.xml;

services:
  - mysql

matrix:
  include:
    - php: 7.2
      dist: trusty
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: "10.1"
    - php: 7.3
      dist: trusty
      env: DB=mysql MARIADB=10.1
      addons:
        mariadb: "10.1"

    - php: 7.2
      dist: trusty
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: "10.2"
    - php: 7.3
      dist: trusty
      env: DB=mysql MARIADB=10.2
      addons:
        mariadb: "10.2"

    - php: 7.2
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: "9.5"
    - php: 7.3
      env: DB=pgsql POSTGRES=9.5
      addons:
        postgresql: "9.5"

    - php: 7.2
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6
    - php: 7.3
      env: DB=pgsql POSTGRES=9.6
      addons:
        postgresql: 9.6

  allow_failures:
    - php: nightly

  fast_finish: true

# cache vendors
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  webhooks:
    - http://propel.jarves.io/build.php
    - https://webhooks.gitter.im/e/206efe76e183f9ade489
